version: "3.8"
services:
    anvil:
        build:
            context: ./smartcontracts
            dockerfile: Dockerfile.anvil
        ports:
            - 8545:8545

    deploy:
        depends_on:
            - anvil
        build:
            context: ./smartcontracts
            dockerfile: Dockerfile.deploy

    frontend:
        depends_on:
            - deploy
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
